Generated by Spark: Getting a couple of errors on page reload:
@supabase_supabase-js.js?v=6587b298:4300  GET https://bgdtbsacfkvjgpkouadc.supabase.co/rest/v1/team_invites?select=*%2Cteam%3Ateams%28*%29&invitee_email=eq.jamiemccallum0%40gmail.com&status=eq.pending&order=created_at.desc 400 (Bad Request)
(anonymous) @ @supabase_supabase-js.js?v=6587b298:4300
(anonymous) @ @supabase_supabase-js.js?v=6587b298:4321
fulfilled @ @supabase_supabase-js.js?v=6587b298:4273
Promise.then
step @ @supabase_supabase-js.js?v=6587b298:4286
(anonymous) @ @supabase_supabase-js.js?v=6587b298:4288
__awaiter6 @ @supabase_supabase-js.js?v=6587b298:4270
(anonymous) @ @supabase_supabase-js.js?v=6587b298:4311
then @ @supabase_supabase-js.js?v=6587b298:90Understand this error
useInvites.ts:34 Error fetching invites: {code: '42703', details: null, hint: null, message: 'column team_invites.invitee_email does not exist'}